---
always_allow_html: 'true'
date: '2020-05-30'
date_start: '2018-12-01'
description: 'Elasticity of demand at price p, given h change in p.

  Point elasticity of demand at price p.

  Elasticity and the limiting definition of derivative.

  '
file: derivative_elasticity
output:
  html_document:
    includes:
      in_header: ../hdga.html
    pandoc_args: ../_output_kniti_html.yaml
  pdf_document:
    includes:
      in_header: ../preamble.tex
    pandoc_args: ../_output_kniti_pdf.yaml
title: Elasticity and Derivative
titleshort: Elasticity and Derivative
urlcolor: blue
---

## Elasticity and Derivative

```{r global_options, include = FALSE}
try(source('../.Rprofile'))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

### Demand and Supply

At price $p_0$, the current price level, the demand and supply of good
$x$ ( $x$ could be capital, labor, apples ect) could be written as:

-   $\displaystyle x_{\textrm{demand}} =\textrm{D}(p_0 )$

-   $\displaystyle x_{\textrm{supply}} =\textrm{S}(p_0 )$

Note that we solve for the maximization problem of the demander of good
$x$ and the supplier of good $x$ at price $p_0$ to find the quantity
demanded and quantity supplied at this particular price. We derive the
demand and supply curves by solving for quantity demanded and supplied
at many prices points and connecting the resulting pairs of price and
quantity demanded and supplied in a graph together.

### How does demand (or supply) respond to a change in price?

What happens to demand and supply if $p_0$ increases to $p_0 +h$?

-   $\displaystyle x_{\textrm{d}} =\textrm{D}(p_0 +h)$

-   $\displaystyle x_{\textrm{s}} =\textrm{S}(p_0 +h)$

With normal goods, we expect that demand for $x$ decreases when price
increases, and supply for $x$ increases when price increases.

### How sensitive are demands to price changes?

If when movie ticket doubles in price, the number of theater goers goes
down just a little bit, perhaps theater chains could make a lot more
money by raising price. In this case, price has a hard time shifting
demand, hence demand is fairly inelastic with respect to price. If
orange juice buyers find apple juice to be largely substitutable, then
if the price of orange juice goes up, demand for orange juice might
decrease a lot as consumers switch to apple juice. In this case, price
has an easy time shifting demand, hence demand is fairly elastic with
repsect to price.

To avoid thinking about the unit of price and unit of goods, we think of
percentage changes: what is the **percent** change in quantity of goods
demanded given a **percent** change in the price of that good?

-   $\displaystyle \frac{\textrm{Percent}\;\textrm{change}\;\textrm{in}\;\textrm{demand}\;\textrm{given}\;h\;\textrm{change}\;\textrm{in}\;\textrm{price}}{\textrm{Percent}\;\textrm{change}\;\textrm{in}\;\textrm{price}\;\textrm{when}\;\textrm{price}\;\textrm{increase}\;\textrm{by}\;h}$

The price elasticity of demand at price $p_0$ given $h$ increase in
price is:

-   $\displaystyle \frac{\left(\frac{\textrm{D}(p_0 +h)-\textrm{D}(p_0 )}{\textrm{D}(p_0 )}\right)}{\left(\frac{p_0 +h-p_0 }{p_0 }\right)}=\left(\frac{\textrm{D}(p_0 +h)-\textrm{D}(p_0 )}{\textrm{D}(p_0 )}\right)\cdot \left(\frac{p_0 }{h}\right)$

If we know how to solve for the optimal demand, we can calculate this at
every point $x_0$ for small $h$.

### Point Elasticity and Derivative

If you solve for the elasticity formula above, you will find that as $h$
decreases, the price elasticity of demand at $p_0$ converges to a
number. The number that the elasticity formula converges to is the
**point price elasticity of demand:**

-   $\displaystyle \textrm{DemandElasticity}(p_0 )=\lim_{h\to 0} \left(\left(\frac{\textrm{D}(p_0 +h)-\textrm{D}(p_0 )}{\textrm{D}(p_0 )}\right)\cdot \left(\frac{p_0 }{h}\right)\right)$

Some of the terms in the fomrula do not include $h$, we can move them
outside of the $\lim$ symbol

-   $\displaystyle \textrm{DemandElasticity}(p_0 )=\left(\lim_{h\to 0} \left(\frac{\textrm{D}(p_0 +h)-\textrm{D}(p_0 )}{h}\right)\right)\cdot \frac{p_0 }{\textrm{D}(p_0 )}$

This should look very familiary, it is exactly the formula for
derivative of the demand funtion at $p_0$.

-   $\displaystyle \textrm{DemandElasticity}(p_0 )={\textrm{D}}^{\prime } (p_0 )\cdot \frac{p_0 }{\textrm{D}(p_0 )}$

This formula applies to all price $p$

-   $\displaystyle \textrm{DemandElasticity}(p_0 )={\textrm{D}}^{\prime } (p)\cdot \frac{p}{\textrm{D}(p)}$

If we can derive the demand function, and it is differentiable over the
domain of $p$, then we can solve analytically for demand elasticity as a
function of $p$.

### **Inelastic, elastic and unit elastic**

If the elasticity is $0$, that means demand is fixed and does not change
with price. If the demand elasticity obtained above is between $0$ and
$-1$, the good is inelastic with respect to price. If the price
elasticity is less than $-1$, the good is elastic with respect to price.
At $1$, the good is unit elastic:

-   $\displaystyle \left\lbrace \begin{array}{c}
    -1<{\textrm{D}}^{\prime } (p)\cdot \frac{p}{\textrm{D}(p)}<0\textrm{,}\;\textrm{inelastic}\\
    {\textrm{D}}^{\prime } (p)\cdot \frac{p}{\textrm{D}(p)}=-1\;\textrm{,}\;\textrm{unit}\;\textrm{elastic}\\
    {\textrm{D}}^{\prime } (p)\cdot \frac{p}{\textrm{D}(p)}<-1\;\textrm{,}\;\textrm{elastic}
    \end{array}\right.$

**Theorem 3.6**: If a good is inelastic, an increasein price leads to an
increase in total expenditure, for an elastic good, an increase in price
leads to a decrease in total expenditures.
