---
always_allow_html: 'true'
core:
- code: 'syms

    diff()

    '
  package: m
date: '2020-05-30'
date_start: '2018-12-01'
description: 'Derivative notations, limit definition, and key rules.

  '
file: derivative_rules
output:
  html_document:
    includes:
      in_header: ../hdga.html
    pandoc_args: ../_output_kniti_html.yaml
  pdf_document:
    includes:
      in_header: ../preamble.tex
    pandoc_args: ../_output_kniti_pdf.yaml
title: Derivative Definition and Rules
titleshort: Derivative Definition and Rules
urlcolor: blue
---

## Derivative Definition and Rules

```{r global_options, include = FALSE}
try(source('../.Rprofile'))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

### Definition

(SB) Let $(x_0 ,f(x_0 ))$ be a point on te graph of $y=f(x)$.

The **derivative** of $f$ at $x_0$ is the slope of the tangent line to
the graph of $f$ at $(x_0 ,f(x_0 ))$.

There are some common ways of denoting derivative of funtion $f$ at
$x_0$:

-   $\displaystyle f^{\prime } (x_0 )$

-   $\displaystyle \frac{df}{dx}(x_0 )$

-   $\displaystyle \frac{dy}{dx}(x_0 )$

-   $f_x (x_0 )$: this is popular in economics

We write this analyticaly as:

$$f^{\prime } (x_0 )=\lim_{h\to 0} \frac{f(x_0 +h)-f(x_0 )}{h}$$

If this limit exists, then the function $f$ is **differentiable** at
$x_0$.

We will use this formula to derive first order taylor approximation. And
this will also appear when we derive the formula for point elasticity.

### Derivative Rules--Constant Rule

given constant $k$,:

-   $\displaystyle f(x)=a\cdot x$

-   $\displaystyle f^{\prime } (x_0 )=a$

<!-- -->

    syms x a
    f(x, a) = a*x

f(x, a) = $\displaystyle a\,x$

    dfk = diff(f,x)

dfk(x, a) = $\displaystyle a$

### Derivative Rules--Power Rule (Polynomial Rule)

(SB) For any positive integer $k$ (or real number $k$), the derivative
of $f(x)=x^k$ at $x_0$ is:

-   $\displaystyle f(x)=x^k$

-   $\displaystyle f^{\prime } (x_0 )=k\cdot x_0^{k-1}$

<!-- -->

    syms x a k
    f(x, a, k) = a*x^k

f(x, a, k) = $\displaystyle a\,x^k$

    dfk = diff(f,x)

dfk(x, a, k) = $\displaystyle a\,k\,x^{k-1}$

### Derivative Rules--Chain Rule

-   $\displaystyle f(x)=p(q(x))$

-   $\displaystyle f^{\prime } (x_0 )=p^{\prime } (q(x_0 ))\cdot q^{\prime } (x_0 )$

<!-- -->

    syms x a k
    f(x, a, k) = (a*x)^k

f(x, a, k) = $\displaystyle {{\left(a\,x\right)}}^k$

    dfk = diff(f,x)

dfk(x, a, k) = $\displaystyle a\,k\,{{\left(a\,x\right)}}^{k-1}$

### Derivative Rules--Sum (and difference) Rule

Given functions $p$ and $q$ that are differentiable at $x$, then:

-   $\displaystyle f(x)=p(x)+q(x)$

-   $\displaystyle f^{\prime } (x)=p^{\prime } (x)+q^{\prime } (x)$

<!-- -->

    syms x a b c d
    f(x, a, b, c, d) = a*x^b + c*x^d

f(x, a, b, c, d) = $\displaystyle a\,x^b +c\,x^d$

    dfk = diff(f,x)

dfk(x, a, b, c, d) = $\displaystyle a\,b\,x^{b-1} +c\,d\,x^{d-1}$

### Derivative Rules--Product Rule

Given functions $p$ and $q$ that are differentiable at $x$, then:

-   $\displaystyle f(x)=p(x)\cdot q(x)$

-   $\displaystyle f^{\prime } (x)=p^{\prime } (x)\cdot q(x)+p(x)\cdot q^{\prime } (x)$

<!-- -->

    syms x a b c d
    f(x, a, b, c) = (a*x^b)*(c*x^d)

f(x, a, b, c) = $\displaystyle a\,c\,x^b \,x^d$

    dfk = diff(f,x)

dfk(x, a, b, c) =
$\displaystyle a\,b\,c\,x^d \,x^{b-1} +a\,c\,d\,x^b \,x^{d-1}$

### Derivative Rules--Quotient Rule

Given functions $p$ and $q$ that are differentiable at $x$, then:

-   $\displaystyle f(x)=\frac{p(x)}{q(x)}$

-   $\displaystyle f^{\prime } (x)=\frac{p^{\prime } (x)\cdot q(x)-p(x)\cdot q^{\prime } (x)}{(q(x))^2 }$

Note that the quotient rule is based on the product rule, because:

-   $\displaystyle f(x)=\frac{p(x)}{q(x)}=p(x)\cdot \frac{1}{q(x)}$

So you can derive the quotient rule formula based on the product rule
where the first term is $p(x)$ and the second term is $\frac{1}{q(x)}$.

    syms x a b c d
    f(x, a, b, c) = (a*x^b)/(c*x^d)

f(x, a, b, c) = $\displaystyle \frac{a\,x^b }{c\,x^d }$

    dfk = diff(f,x)

dfk(x, a, b, c) =
$\displaystyle \frac{a\,b\,x^{b-1} }{c\,x^d }-\frac{a\,d\,x^b }{c\,x^{d+1} }$

### Derivative Rules--Exponential 

We use exponential functions in economnics a lot:

-   $\displaystyle f(x)=\exp (a\cdot x)$

-   $\displaystyle f^{\prime } (x)=a\cdot \exp (a\cdot x)$

<!-- -->

    syms x a
    f(x, a) = exp(a*x)

f(x, a) = $\displaystyle {\mathrm{e}}^{a\,x}$

    dfk = diff(f,x)

dfk(x, a) = $\displaystyle a\,{\mathrm{e}}^{a\,x}$

This is a special case of any power function

-   $\displaystyle f(x)=c^{a\cdot x}$

-   $\displaystyle f^{\prime } (x)=a\cdot (\log c)\cdot c^{a\cdot x}$

note that $log(exp(c))=c$

    syms x a c
    f(x, a, c) = c^(a*x)

f(x, a, c) = $\displaystyle c^{a\,x}$

    dfk = diff(f,x)

dfk(x, a, c) = $\displaystyle a\,c^{a\,x} \,\log \left(c\right)$

### Derivative Rules--Log 

We use Log functions in economnics a lot:

-   $\displaystyle f(x)=\log (a\cdot x)$

-   $\displaystyle f^{\prime } (x)=\frac{1}{x}$

note that the c cancels out.

    syms x a
    f(x, a) = log(a*x)

f(x, a) = $\displaystyle \log \left(a\,x\right)$

    dfk = diff(f,x)

dfk(x, a) = $\displaystyle \frac{1}{x}$
