---
always_allow_html: 'true'
date: '2020-05-30'
date_start: '2018-12-01'
description: 'Consistent function naming.

  '
file: funcnotations
output:
  html_document:
    includes:
      in_header: ../hdga.html
    pandoc_args: ../_output_kniti_html.yaml
  pdf_document:
    includes:
      in_header: ../preamble.tex
    pandoc_args: ../_output_kniti_pdf.yaml
title: Function Notations
titleshort: Function Notations
urlcolor: blue
---

## Function Notations

```{r global_options, include = FALSE}
try(source('../.Rprofile'))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

When you read your first economic papers, perhaps you are confused about
function notation. Economic models include potentially a lot of
variables, and different notations are used based on personal
preference. Make sure you use consistent notations, and state clearly
what your notations mean.

In general, the letter $f$ represents a particular rule of mapping, if
there are multiple functional relationships in an economic model,
different letters could be used, for example:

$$y=f(h),l=g(h),u=w(h)$$

These three equations could be from a model where:

-   $h$ is the number of hours an individual works

-   $y$ is the income that the individual makes as a function of work
    hours

-   $l$ is the number of leisure hours remaining as a function work
    hours

-   $u$ is the overall level of utility as a function of work hours.

Sometimes we have to write down many functions, and we can potentially
run out of letters. Hence, you might potentially want to use
superscripts:

$$y=f^y (h),l=f^l (h),u=f^w (h)$$

or we could use the same letter for function as the letter for the value
of the function, although this could be confusing because the function
mapping would have the same notation as a value of the function:

$$y=y(h),l=l(h),u=u(h)$$

if the above notation seems unclear, you can perhaps use more cursive
letters for functions, latex offers different fonts/typesetting options:

$$y=\mathcal{y}(h),l=\mathcal{l}(h),u=\mathcal{u}(h)$$

Again, make sure you are clear about what your notations mean. Math
should help make our econ ideas more clear to ourselves and others, and
that starts with clear functional notations.
