---
always_allow_html: 'true'
date: '2020-05-30'
date_start: '2018-12-01'
description: 'Constrained on capital/borrowing, solve for cases.

  If constraint binds, re-optimize labor choice given capital bound.

  '
file: KL_borrowhire_firm_inqc
output:
  html_document:
    includes:
      in_header: ../hdga.html
    pandoc_args: ../_output_kniti_html.yaml
  pdf_document:
    includes:
      in_header: ../preamble.tex
    pandoc_args: ../_output_kniti_pdf.yaml
title: Borrowing Constrained Firm's Profit Maximization Problem with Cobb Douglas
  Production Function
titleshort: Firm Profit Maximization Problem with Borrowing Constraint
urlcolor: blue
---

## Borrowing Constrained Profit Maximization

```{r global_options, include = FALSE}
try(source('../.Rprofile'))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

In this problem, we solve the constrained firm's profit maximization
problem with decreasing returns to scale. This continues from the
unconstrained profit maximization problem from [Firm's Profit
Maximization Problem with Cobb Douglas Production Function (Decreasing
Returns to
Scale)](https://fanwangecon.github.io/Math4Econ/matrix_application/KL_borrowhire_firm.html).

### Firm and Capital and Labor

The problem is the same as before, the profit maximization problem is:

-   $\displaystyle \max_{K,L} \left(p\cdot A\cdot K^{\alpha } \cdot L^{\beta } -r\cdot K-w\cdot L\right)$

The constraint is such that the firm can not borrow more than $\bar{K}$

-   $\displaystyle K\le \bar{K}$

To find optimal choices, we will assume that $\alpha +\beta <1$

### Lagrangian and First Order Conditions

$$\mathcal{L}=\left(p\cdot A\cdot K^{\alpha } \cdot L^{\beta } -r\cdot K-w\cdot L\right)-\lambda \left(K-\bar{K} \right)$$

-   $\displaystyle \frac{\partial \mathcal{L}}{\partial K}:\alpha \cdot p\cdot A\cdot K^{\alpha -1} \cdot L^{\beta } -r=\lambda$

-   $\displaystyle \frac{\partial \mathcal{L}}{\partial L}:\beta \cdot p\cdot A\cdot K^{\alpha } \cdot L^{\beta -1} -w=\lambda$

-   $\displaystyle \lambda \left(K-\bar{K} \right)=0$

-   $\displaystyle \lambda \ge 0$

-   $\displaystyle K<\bar{K}$

If the optimal unconstrained capital choice is less than $\bar{K}$, then
the inequality constraint can not impact optimal choices. The inequality
constraint should disappear from the lagrangian, which is achieved with
$\lambda =0$.

If the optimal constrained capital choice would have been greater than
$\bar{K}$, then the constraint is binding, in the sense that the
$\bar{K}$ bound will limit the firm from borrowing optimally. The firm
will borrow as much as it can so that $K=\bar{K}$. Since $K-\bar{K} =0$,
$\lambda \ge 0$. Note that the larger $\lambda$ is, the greater the gap
between marginal productivity and marginal cost.

### Solving for Different Cases

When faced with inequality constrained problems, we have to solve the
problem in different possible cases in which different combinations of
the inequality constraints present would be binding. Then we compare
across cases to find the case that maximized the objective.

Our problem here is simpler, we only have two cases:

1.  The inequality constraint does not bind, which means we can use the
    optimal unconstrained capital and labor choices we found previously
    in [Firm's Profit Maximization Problem with Cobb Douglas Production
    Function (Decreasing Returns to
    Scale)](https://fanwangecon.github.io/Math4Econ/matrix_application/KL_borrowhire_firm.html).

2.  The inequality constraint does bind for capital, which means we
    solve for optimal labor choice given fixed level of capital. This is
    exactly what we did in [Firm's Profit Maximization Problem and
    Optimal Capital
    Choice](https://fanwangecon.github.io/Math4Econ/derivative_application/K_borrow_firm.html),
    except there we solve for optimal capital fixing labor. Now we need
    to solve for optimal labor fixing capital at the constraint.

### Solution

With *con* denoting constrained, *unc* denoting unconstrained, we have:

$$K^{\textrm{con}} =\left\lbrace \begin{array}{c}
K^{\textrm{unc}} \textrm{,}\;\textrm{if}\;K^{\textrm{unc}} <\bar{K} \\
\bar{K} \textrm{,}\;\textrm{otherwise}
\end{array}\right.$$

$$L^{\textrm{con}} =\left\lbrace \begin{array}{c}
L^{\textrm{unc}} \textrm{,}\;\textrm{if}\;K^{\textrm{unc}} <\bar{K} \\
\arg \max_L \Pi \left(\bar{K} ,L;r,w\right)\textrm{,}\;\textrm{otherwise}
\end{array}\right.$$
